version: "3.8"

services:
  service:
    image: registry.digitalocean.com/jur-jbp/jur-node:13JUL2022-2
    container_name: jur_node_container
    command: jur-node --chain jur-testnet --port 30333 --ws-port 9944 --rpc-port 9933 --validator --bootnodes /ip4/35.209.0.147/tcp/30333/p2p/12D3KooWBBb45AWo5cnFhurPav2aSgpsPewPfLmEdCW8Xw7wiuAF
    volumes:
      - data:/data
    restart: always
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944
      - 9615:9615

volumes:
  data:
