version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0
  docker: circleci/docker@1.7.0
  gcp-gcr: circleci/gcp-gcr@0.15.1

# Commands
commands:
  install_latest_terraform:
    description: "Install latest terraform"
    steps:
      - run:
          name: Install latest terraform
          command: wget -nv https://releases.hashicorp.com/terraform/1.4.5/terraform_1.4.5_linux_amd64.zip && unzip terraform_1.4.5_linux_amd64.zip && mv terraform /usr/local/bin && terraform -v
# Jobs
jobs:
  validate_infrastructure:
    description: "Validate Infrastructure"
    executor: terraform/default
    steps:
      - checkout
      - install_latest_terraform
      - terraform/init:
          path: infrastructure
      - terraform/validate:
          path: infrastructure
      - terraform/fmt:
          path: infrastructure
    working_directory: ~/src

  apply_infrastructure:
    parameters:
      sub_domain:
        type: string
      deployment_environment:
        type: string
    description: "Apply Infrastructure"
    executor: terraform/default
    environment:
      TF_VAR_SUB_DOMAIN: << parameters.sub_domain >>
      TF_VAR_DEPLOYMENT_ENVIRONMENT: << parameters.deployment_environment >>
    steps:
      - checkout
      - install_latest_terraform
      - terraform/plan:
          backend_config: "prefix=staging-l1-jur-node"
          path: infrastructure
      - terraform/apply:
          backend_config: "prefix=staging-l1-jur-node"
          path: infrastructure
    working_directory: ~/src

  build_and_push_docker_image:
    description: "Build and Push Docker Image"
    executor: gcp-gcr/default
    resource_class: xlarge
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CREDENTIALS
      - gcp-gcr/build-image:
          image: jur-node
          no_output_timeout: 20m
          registry-url: us.gcr.io
      - gcp-gcr/push-image:
          image: jur-node
          registry-url: us.gcr.io

# Workflows
workflows:
  staging:
    jobs:
      - validate_infrastructure:
          filters:
            branches:
              only: feat/cicd
      - approve_infrastructure:
          description: "Approve Infrastructure"
          type: approval
          requires:
            - validate_infrastructure
      - apply_infrastructure:
          sub_domain: "testnet"
          deployment_environment: "staging"
          requires:
            - approve_infrastructure
      - build_and_push_docker_image:
          requires:
            - apply_infrastructure
