version: "3.8"

services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/certificate:/etc/ssl/certs
      - /home/circleci/html:/html
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - jur-node
  jur-node:
    image: us.gcr.io/layer1-mvp/jur-node:latest
    command:
      - /bin/bash
      - -c
      - |
        jur-node key insert --chain ./jurTestnetSpecRaw.json --scheme Sr25519 --suri $KEY_SET_AURA_1 --key-type aura 
        jur-node key insert --chain ./jurTestnetSpecRaw.json --scheme Ed25519 --suri $KEY_SET_GRANPA_1 --key-type gran 
        jur-node --chain ./jurTestnetSpecRaw.json --port 30333 --ws-port 9945 --rpc-port 9933 --validator --rpc-methods Unsafe
    working_dir: /res
    volumes:
      - ../res:/res
    ports:
      - 30333:30333
      - 9933:9933
      - 9945:9945
    restart: unless-stopped
