version: "3.8"

services:
  web:
    image: nginx:latest
    volumes:
      - ${PWD}/nginx/config/testnet.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificate:/etc/ssl/certs
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - jur-node
  jur-node:
    image: deployment_jur-node:latest
    command: sleep infinity
    working_dir: /res
    volumes:
      - ../res:/res
    ports:
      - 30333:30333
      - 9933:9933
    restart: unless-stopped
