
//! Autogenerated weights for pallet_events
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-12-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Pankajs-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/jur-node
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet-events
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/event/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_events.
pub trait WeightInfo {
	fn create_event() -> Weight;
	fn proof_of_presence() -> Weight;
}

/// Weights for pallet_events using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Community::Communities` (r:1 w:0)
	/// Proof: `Community::Communities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Passport::Badges` (r:1 w:0)
	/// Proof: `Passport::Badges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EventPallet::NextEventId` (r:1 w:1)
	/// Proof: `EventPallet::NextEventId` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EventPallet::Events` (r:0 w:1)
	/// Proof: `EventPallet::Events` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_event() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1197`
		//  Estimated: `4662`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(29_000_000, 4662)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

	fn proof_of_presence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1197`
		//  Estimated: `4662`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(39_000_000, 4662)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `Community::Communities` (r:1 w:0)
	/// Proof: `Community::Communities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Passport::Badges` (r:1 w:0)
	/// Proof: `Passport::Badges` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EventPallet::NextEventId` (r:1 w:1)
	/// Proof: `EventPallet::NextEventId` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EventPallet::Events` (r:0 w:1)
	/// Proof: `EventPallet::Events` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_event() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1197`
		//  Estimated: `4662`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(29_000_000, 4662)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

	fn proof_of_presence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1197`
		//  Estimated: `4662`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(39_000_000, 4662)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}