
//! Autogenerated weights for pallet_proposal
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-07-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBook-Pro.local`, CPU: `Apple M1 pro`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/jur-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet-proposal
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/proposal/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_proposal.
pub trait WeightInfo {
	fn create_proposal() -> Weight;
	fn cast_vote() -> Weight;
}

/// Weights for pallet_proposal using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Community Communities (r:1 w:0)
	/// Proof Skipped: Community Communities (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal NextProposalId (r:1 w:1)
	/// Proof Skipped: Proposal NextProposalId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Proposal NextChoiceId (r:1 w:1)
	/// Proof Skipped: Proposal NextChoiceId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Proposal ProposalDetails (r:1 w:1)
	/// Proof Skipped: Proposal ProposalDetails (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal ProposalExpireTime (r:0 w:1)
	/// Proof Skipped: Proposal ProposalExpireTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Proposals (r:0 w:1)
	/// Proof Skipped: Proposal Proposals (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Choices (r:0 w:1)
	/// Proof Skipped: Proposal Choices (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Votes (r:0 w:4)
	/// Proof Skipped: Proposal Votes (max_values: None, max_size: None, mode: Measured)
	fn create_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `736`
		//  Estimated: `15788`
		// Minimum execution time: 43_000_000 picoseconds.
		Weight::from_parts(44_000_000, 15788)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	/// Storage: Community Communities (r:1 w:0)
	/// Proof Skipped: Community Communities (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Proposals (r:1 w:1)
	/// Proof Skipped: Proposal Proposals (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Choices (r:1 w:0)
	/// Proof Skipped: Proposal Choices (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Votes (r:1 w:1)
	/// Proof Skipped: Proposal Votes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal ProposalDetails (r:1 w:1)
	/// Proof Skipped: Proposal ProposalDetails (max_values: None, max_size: None, mode: Measured)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1387`
		//  Estimated: `24260`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(39_000_000, 24260)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Community Communities (r:1 w:0)
	/// Proof Skipped: Community Communities (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal NextProposalId (r:1 w:1)
	/// Proof Skipped: Proposal NextProposalId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Proposal NextChoiceId (r:1 w:1)
	/// Proof Skipped: Proposal NextChoiceId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Proposal ProposalDetails (r:1 w:1)
	/// Proof Skipped: Proposal ProposalDetails (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal ProposalExpireTime (r:0 w:1)
	/// Proof Skipped: Proposal ProposalExpireTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Proposals (r:0 w:1)
	/// Proof Skipped: Proposal Proposals (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Choices (r:0 w:1)
	/// Proof Skipped: Proposal Choices (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Votes (r:0 w:4)
	/// Proof Skipped: Proposal Votes (max_values: None, max_size: None, mode: Measured)
	fn create_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `736`
		//  Estimated: `15788`
		// Minimum execution time: 43_000_000 picoseconds.
		Weight::from_parts(44_000_000, 15788)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	/// Storage: Community Communities (r:1 w:0)
	/// Proof Skipped: Community Communities (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Proposals (r:1 w:1)
	/// Proof Skipped: Proposal Proposals (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Choices (r:1 w:0)
	/// Proof Skipped: Proposal Choices (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal Votes (r:1 w:1)
	/// Proof Skipped: Proposal Votes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Proposal ProposalDetails (r:1 w:1)
	/// Proof Skipped: Proposal ProposalDetails (max_values: None, max_size: None, mode: Measured)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1387`
		//  Estimated: `24260`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(39_000_000, 24260)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}