
//! Autogenerated weights for pallet_token_swap
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ayushs-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/jur-node
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet-token-swap
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/token-swap/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_token_swap.
pub trait WeightInfo {
	fn update_state_root() -> Weight;
	fn claim() -> Weight;
}

/// Weights for pallet_token_swap using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: TokenSwap RootInformation (r:0 w:1)
	/// Proof Skipped: TokenSwap RootInformation (max_values: Some(1), max_size: None, mode: Measured)
	fn update_state_root() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: TokenSwap RootInformation (r:1 w:0)
	// Storage: TokenSwap LatestClaimedBalance (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn claim() -> Weight {
		Weight::from_parts(61_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: TokenSwap RootInformation (r:0 w:1)
	/// Proof Skipped: TokenSwap RootInformation (max_values: Some(1), max_size: None, mode: Measured)
	fn update_state_root() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: TokenSwap RootInformation (r:1 w:0)
	// Storage: TokenSwap LatestClaimedBalance (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn claim() -> Weight {
		Weight::from_parts(61_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}