
//! Autogenerated weights for pallet_whitelist
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-10-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Pankajs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/jur-node
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet-whitelist
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/whitelist/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_whitelist.
pub trait WeightInfo {
	fn add_founder() -> Weight;
	fn revoke_founder() -> Weight;
	fn add_admin() -> Weight;
	fn revoke_admin() -> Weight;
}

/// Weights for pallet_whitelist using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Whitelist::Founders` (r:1 w:1)
	/// Proof: `Whitelist::Founders` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_founder() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 1491)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Whitelist::Founders` (r:1 w:1)
	/// Proof: `Whitelist::Founders` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn revoke_founder() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `64`
		//  Estimated: `1549`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 1549)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Whitelist::Admins` (r:1 w:1)
	/// Proof: `Whitelist::Admins` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 1491)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Whitelist::Admins` (r:1 w:1)
	/// Proof: `Whitelist::Admins` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn revoke_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `64`
		//  Estimated: `1549`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 1549)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `Whitelist::Founders` (r:1 w:1)
	/// Proof: `Whitelist::Founders` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_founder() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 1491)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Whitelist::Founders` (r:1 w:1)
	/// Proof: `Whitelist::Founders` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn revoke_founder() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `64`
		//  Estimated: `1549`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 1549)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Whitelist::Admins` (r:1 w:1)
	/// Proof: `Whitelist::Admins` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn add_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 1491)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Whitelist::Admins` (r:1 w:1)
	/// Proof: `Whitelist::Admins` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn revoke_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `64`
		//  Estimated: `1549`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 1549)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}