name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set-Up
      run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev protobuf-compiler

    - name: Install Rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env
        rustup default stable
        rustup update nightly
        rustup update stable
        rustup toolchain install nightly
        rustup target add wasm32-unknown-unknown --toolchain nightly

    - name: Check format
      run: cargo fmt --all -- --check

    - name: Build
      run: SKIP_WASM_BUILD= cargo check --all-targets --features runtime-benchmarks
      
    - name: Test
      run: SKIP_WASM_BUILD= cargo test --workspace --features runtime-benchmarks -- --nocapture
